In [1]:
import numpy as np 
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression

df = pd.read_csv(r"D:\MYFolder( Extra Effort)\DATASETS\user_behavior_dataset.csv")

In [2]:
df.head()

,User ID,Device Model,Operating System,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender,User Behavior Class
0,1,Google Pixel 5,Android,393,6.4,1872,67,1122,40,Male,4
1,2,OnePlus 9,Android,268,4.7,1331,42,944,47,Female,3
2,3,Xiaomi Mi 11,Android,154,4.0,761,32,322,42,Male,2
3,4,Google Pixel 5,Android,239,4.8,1676,56,871,20,Male,3
4,5,iPhone 12,iOS,187,4.3,1367,58,988,31,Female,3

In [3]:
#Predict Data Usage

columns = ['App Usage Time (min/day)', 'Battery Drain (mAh/day)',
       'Number of Apps Installed', 'Data Usage (MB/day)', 'Age']

data = df[columns]

In [4]:
data.head()

,App Usage Time (min/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age
0,393,1872,67,1122,40
1,268,1331,42,944,47
2,154,761,32,322,42
3,239,1676,56,871,20
4,187,1367,58,988,31

In [5]:
#%%Separate Features and test-train data

feature_name = ['App Usage Time (min/day)', 'Battery Drain (mAh/day)',
       'Number of Apps Installed', 'Age']
target = ['Data Usage (MB/day)']

In [6]:
X = data[feature_name]
y = data[target]

In [7]:
X

,App Usage Time (min/day),Battery Drain (mAh/day),Number of Apps Installed,Age
0,393,1872,67,40
1,268,1331,42,47
2,154,761,32,42
3,239,1676,56,20
4,187,1367,58,31
...,...,...,...,...
695,92,1082,26,22
696,316,1965,68,59
697,99,942,22,50
698,62,431,13,44
699,212,1306,49,23

In [8]:
y

     Data Usage (MB/day)
0                   1122
1                    944
2                    322
3                    871
4                    988
..                   ...
695                  381
696                 1201
697                  457
698                  224
699                  828

[700 rows x 1 columns]

In [9]:


test_data = 0.2
seed = 10
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_data, random_state=seed)

In [10]:
X_train.shape

(560, 4)

In [11]:
y_train.shape

(560, 1)

In [11]:
y_test.shape

(140, 1)

In [12]:
X_test.shape

(140, 4)

In [12]:
#%% Train the Regression Model
regr = LinearRegression() 
regr.fit(X_train, y_train)

LinearRegression()

In [13]:
#%% Find predictions from trained model
y_pred = regr.predict(X_test)

In [14]:
y_test

     Data Usage (MB/day)
27                  1599
641                  255
152                  396
302                 1086
541                  537
..                   ...
65                   917
76                   122
519                  371
431                  506
497                  362

[140 rows x 1 columns]

In [15]:
y_pred

array([[1758.00633409],
       [ 134.31621938],
       [ 467.35993414],
       [1518.72468403],
       [ 435.08186569],
       [1914.741396  ],
       [ 166.28068995],
       [ 173.68622234],
       [ 137.49761344],
       [1289.65076461],
       [ 923.8283987 ],
       [ 424.35089884],
       [ 891.52425385],
       [1230.7437267 ],
       [1224.15523076],
       [1462.40350908],
       [ 973.702166  ],
       [ 123.11529918],
       [ 156.21992118],
       [ 388.83979723],
       [ 412.88848045],
       [1003.42548855],
       [ 110.95639658],
       [ 933.05204663],
       [1844.05830036],
       [1421.58419025],
       [1507.48954081],
       [1485.61325354],
       [ 854.61935213],
       [ 446.02213732],
       [ 105.074366  ],
       [ 829.48918153],
       [ 897.02911266],
       [ 535.39455039],
       [ 891.36993487],
       [ 385.19297079],
       [ 846.46907294],
       [ 502.55977453],
       [1740.9118428 ],
       [1858.69002988],
       [ 160.4461152 ],
       [ 749.93383639],
       [1289.6455169 ],
       [ 438.643503  ],
       [ 212.75882614],
       [ 379.86815272],
       [ 462.26160392],
       [ 134.85679437],
       [1342.54685899],
       [1863.15835527],
       [1942.59404171],
       [ 183.54995171],
       [ 193.14882566],
       [1234.4360122 ],
       [1796.73936071],
       [1572.36523366],
       [1872.33842961],
       [ 539.72462385],
       [ 461.56969365],
       [ 977.61432185],
       [1798.3397562 ],
       [1798.89182226],
       [ 462.81490457],
       [1473.48495818],
       [1368.11332505],
       [1769.14201381],
       [1918.11605476],
       [ 530.77733823],
       [ 342.85507098],
       [1841.82365423],
       [ 575.78715427],
       [ 806.21978045],
       [1255.57613911],
       [ 753.98975622],
       [1846.13367339],
       [1277.61126405],
       [1199.91838471],
       [1823.92492848],
       [1372.40177357],
       [1281.08511922],
       [ 551.31767891],
       [1560.76301111],
       [1209.35664963],
       [ 579.45350193],
       [ 950.92708067],
       [ 125.95848296],
       [ 750.27472301],
       [1520.9266542 ],
       [ 134.07517542],
       [ 947.54551491],
       [ 867.24071915],
       [ 180.77739554],
       [ 206.38551022],
       [ 801.30913914],
       [1786.24359949],
       [ 840.77416159],
       [ 821.26015681],
       [ 343.78163248],
       [1211.27928312],
       [1718.43010652],
       [1771.96437822],
       [ 154.1801057 ],
       [ 439.06441137],
       [ 768.50546961],
       [1735.28729745],
       [ 224.1383825 ],
       [ 833.89836598],
       [1403.54888684],
       [ 534.24450325],
       [1800.71270669],
       [ 427.11220611],
       [ 397.621869  ],
       [ 857.96200602],
       [ 114.26087547],
       [ 406.60226578],
       [ 139.73776646],
       [1385.05521183],
       [ 124.54859903],
       [ 250.53543819],
       [ 884.92964465],
       [ 221.78067396],
       [ 377.91689652],
       [ 180.21976797],
       [ 106.39681191],
       [1503.99952165],
       [ 117.89186809],
       [ 852.08334552],
       [1226.30528597],
       [1756.59955667],
       [  90.51804697],
       [ 164.26830977],
       [ 344.59402946],
       [ 920.01154816],
       [1851.33607624],
       [ 921.06165265],
       [ 825.02939055],
       [ 122.8880987 ],
       [ 412.21321765],
       [ 545.38215896],
       [ 430.4833864 ]])

In [17]:
result=y_pred-y_test
result

     Data Usage (MB/day)
27            159.006334
641          -120.683781
152            71.359934
302           432.724684
541          -101.918134
..                   ...
65            -91.970609
76              0.888099
519            41.213218
431            39.382159
497            68.483386

[140 rows x 1 columns]

In [27]:
std_dev=np.std(result)

d:\Users\bsit22f.0007\AppData\Local\anaconda3\Lib\site-packages\numpy\_core\fromnumeric.py:4109: FutureWarning: The behavior of DataFrame.std with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return std(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)

In [19]:
#%% Compute the Errors
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error
  
mae = mean_absolute_error(y_true=y_test, y_pred=y_pred) 
#squared True returns MSE value, False returns RMSE value. 
mse = mean_squared_error(y_true=y_test, y_pred=y_pred) #default=True 
rmse = root_mean_squared_error(y_true=y_test, y_pred=y_pred) 
  
print("MAE:",mae) 
print("MSE:",mse) 
print("RMSE:",rmse)
# print("StandardDeviation:",std_dev)

MAE: 135.3776104114348
MSE: 32989.40114067297
RMSE: 181.6298465029164

In [18]:

#%% K Fold Cross Validation

from sklearn.model_selection import cross_val_score
regr = LinearRegression()

In [19]:
n_splits = 10
scores = cross_val_score(regr, X, y, scoring='neg_root_mean_squared_error', cv=n_splits)
print("Score: ",scores)
rmse_scores = -scores
print("Scores:", rmse_scores)
print("Mean:", rmse_scores.mean())
print("StandardDeviation:", rmse_scores.std())

Score:  [-208.07146312 -186.60472064 -199.84415656 -205.39189628 -201.88750901
 -211.3250211  -173.49433431 -213.91405771 -208.35542147 -181.18592481]
Scores: [208.07146312 186.60472064 199.84415656 205.39189628 201.88750901
 211.3250211  173.49433431 213.91405771 208.35542147 181.18592481]
Mean: 199.00745050123106
StandardDeviation: 13.098014795285204

In [29]:
#%% Logistic Regression (Classification)
#Predict User Behavior Class
columns = ['App Usage Time (min/day)', 'Battery Drain (mAh/day)',
       'Number of Apps Installed', 'Data Usage (MB/day)', 'Age', 'User Behavior Class']

data = df[columns]

In [30]:
feature_name = ['App Usage Time (min/day)', 'Battery Drain (mAh/day)',
       'Number of Apps Installed', 'Age', 'Data Usage (MB/day)']
target = ['User Behavior Class']

In [31]:
data['User Behavior Class'].value_counts()

User Behavior Class
2    146
3    143
4    139
5    136
1    136
Name: count, dtype: int64

In [31]:
X = data[feature_name]
y = data[target]

test_data = 0.2
seed = 10
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = test_data, random_state=seed)

In [32]:
#%% Train the Regression Model
classifier = LogisticRegression() 
classifier.fit(X_train, y_train)

d:\Users\bsit22f.0007\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
d:\Users\bsit22f.0007\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [33]:
#%% Find predictions from trained model
y_pred = classifier.predict(X_test)

In [36]:
y_pred

array([5, 2, 2, 4, 5, 5, 1, 2, 1, 5, 3, 2, 3, 3, 3, 4, 3, 1, 1, 3, 2, 3,
       1, 2, 5, 4, 4, 4, 3, 2, 1, 3, 3, 2, 4, 2, 3, 3, 5, 5, 2, 3, 3, 2,
       1, 3, 3, 1, 4, 4, 5, 1, 1, 4, 5, 5, 5, 2, 2, 3, 5, 5, 1, 5, 4, 5,
       5, 2, 4, 5, 3, 2, 4, 3, 4, 3, 4, 5, 4, 3, 2, 4, 4, 2, 3, 1, 3, 5,
       1, 4, 4, 1, 2, 4, 5, 3, 2, 2, 4, 5, 5, 1, 5, 3, 5, 1, 3, 4, 2, 4,
       1, 2, 3, 1, 2, 1, 5, 1, 1, 2, 1, 2, 1, 1, 5, 1, 4, 3, 4, 1, 1, 1,
       2, 5, 3, 2, 1, 1, 2, 2])

In [37]:
y_test

     User Behavior Class
27                     5
641                    1
152                    2
302                    4
541                    2
..                   ...
65                     3
76                     1
519                    2
431                    2
497                    2

[140 rows x 1 columns]

In [34]:
from sklearn.metrics import accuracy_score
print("Logistic Regression model accuracy(in %):",
      accuracy_score(y_test, y_pred)*100)

Logistic Regression model accuracy(in %): 69.28571428571428

In [35]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.87      0.87      0.87        30
           2       0.66      0.61      0.63        31
           3       0.62      0.62      0.62        29
           4       0.60      0.56      0.58        27
           5       0.70      0.83      0.76        23

    accuracy                           0.69       140
   macro avg       0.69      0.70      0.69       140
weighted avg       0.69      0.69      0.69       140